/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ifpr.crudta.main;

/**
 *
 * @author IFPR
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private UsuariosJInternalFrame usuariosJIF;
    
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        usuariosJIF = new UsuariosJInternalFrame(this);
        initComponents();
        
        painelPrincipal.add(usuariosJIF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        arquivoMenu = new javax.swing.JMenu();
        exportarMNI = new javax.swing.JMenuItem();
        sairMNI = new javax.swing.JMenuItem();
        admMenu = new javax.swing.JMenu();
        usuariosMNI = new javax.swing.JMenuItem();
        produtosMNI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        arquivoMenu.setText("Arquivo");
        arquivoMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        exportarMNI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exportarMNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exportarMNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-plus-white.png"))); // NOI18N
        exportarMNI.setText("Exportar");
        exportarMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarMNIActionPerformed(evt);
            }
        });
        arquivoMenu.add(exportarMNI);

        sairMNI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        sairMNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sairMNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out-white.png"))); // NOI18N
        sairMNI.setText("Sair");
        sairMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMNIActionPerformed(evt);
            }
        });
        arquivoMenu.add(sairMNI);

        jMenuBar1.add(arquivoMenu);

        admMenu.setText("Administração");
        admMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        usuariosMNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuariosMNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-white.png"))); // NOI18N
        usuariosMNI.setText("Usuários");
        usuariosMNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosMNIActionPerformed(evt);
            }
        });
        admMenu.add(usuariosMNI);

        produtosMNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        produtosMNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-bag-white.png"))); // NOI18N
        produtosMNI.setText("Produtos");
        admMenu.add(produtosMNI);

        jMenuBar1.add(admMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportarMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarMNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportarMNIActionPerformed

    private void usuariosMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosMNIActionPerformed
        usuariosJIF.setVisible(true);
    }//GEN-LAST:event_usuariosMNIActionPerformed

    private void sairMNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMNIActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairMNIActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu admMenu;
    private javax.swing.JMenu arquivoMenu;
    private javax.swing.JMenuItem exportarMNI;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JMenuItem produtosMNI;
    private javax.swing.JMenuItem sairMNI;
    private javax.swing.JMenuItem usuariosMNI;
    // End of variables declaration//GEN-END:variables
}
