/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ifpr.crudta.main;

import ifpr.crudta.usuario.SexoPessoa;
import ifpr.crudta.usuario.dao.UsuarioDAO;
import ifpr.crudta.usuario.Usuario;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author IFPR
 */
public class UsuarioFormJDialog extends javax.swing.JDialog {

    private UsuarioDAO usuarioDAO;
    private Usuario usuario;
    private Border bordaOriginal;
    private Border bordaVermelha;

    /**
     * Creates new form usuarioFormJDialog
     */
    public UsuarioFormJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        usuarioDAO = new UsuarioDAO();
        initComponents();
        bordaOriginal = nomeTF.getBorder();
        bordaVermelha = BorderFactory.createLineBorder(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoGrupoRB = new javax.swing.ButtonGroup();
        painelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dataNascimentoTF = new javax.swing.JFormattedTextField();
        cpfTF = new javax.swing.JFormattedTextField();
        masculinoRB = new javax.swing.JRadioButton();
        femininoRB = new javax.swing.JRadioButton();
        outroRB = new javax.swing.JRadioButton();
        cancelarBT = new javax.swing.JButton();
        salvarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Dados do Usuário");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("* Nome:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("* Email:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Data de Nascimento:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("* CPF:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Gênero:");

        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        jLabel7.setText("* Dados Obrigatórios");

        try {
            dataNascimentoTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoTFActionPerformed(evt);
            }
        });

        try {
            cpfTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        sexoGrupoRB.add(masculinoRB);
        masculinoRB.setText("Masculino");
        masculinoRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoRBActionPerformed(evt);
            }
        });

        sexoGrupoRB.add(femininoRB);
        femininoRB.setText("Feminino");

        sexoGrupoRB.add(outroRB);
        outroRB.setText("Outros");

        cancelarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-circle.png"))); // NOI18N
        cancelarBT.setText("Cancelar");
        cancelarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBTActionPerformed(evt);
            }
        });

        salvarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        salvarBT.setText("Salvar");
        salvarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTF)
                    .addComponent(dataNascimentoTF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cpfTF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeTF)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(salvarBT)
                                .addGap(18, 18, 18)
                                .addComponent(cancelarBT))
                            .addComponent(jLabel3)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masculinoRB)
                                .addGap(18, 18, 18)
                                .addComponent(femininoRB)
                                .addGap(18, 18, 18)
                                .addComponent(outroRB))
                            .addComponent(jLabel7))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNascimentoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(masculinoRB)
                    .addComponent(femininoRB)
                    .addComponent(outroRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBT)
                    .addComponent(salvarBT))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void dataNascimentoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoTFActionPerformed

    private void masculinoRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculinoRBActionPerformed

    private void cancelarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBTActionPerformed

    private void salvarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTActionPerformed
        if (isFormValid()) {
            usuario = new Usuario();
            usuario.setNome(nomeTF.getText().trim());
            usuario.setEmail(emailTF.getText().trim());
            usuario.setCpf(cpfTF.getText().trim());
            
            sexoGrupoRB.getSelection();
            if(femininoRB.isSelected()) {
                usuario.setSexoPessoa(SexoPessoa.FEMININO);
            } else if(masculinoRB.isSelected()){
                usuario.setSexoPessoa(SexoPessoa.MASCULINO);
            }else {
                usuario.setSexoPessoa(SexoPessoa.OUTRO);
            }
            
            String dtNascimento = dataNascimentoTF.getText().trim();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dataNascimento = LocalDate.parse(dtNascimento, dtf);
            
            usuarioDAO.create(usuario);
            JOptionPane.showMessageDialog(this, 
                    "Usuario criado com sucesso!",
                    "SUCESSO",
                    JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erro no formulario, verfique os campos em vermelho", "ERRODE VALIDAÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_salvarBTActionPerformed

    private boolean isFormValid() {
        boolean isValid = true;

        if (nomeTF.getText().trim().equals("")) {
            isValid = false;
            nomeTF.setBorder(bordaVermelha);
        } else {
            nomeTF.setBorder(bordaOriginal);
        }

        if (emailTF.getText().trim().equals("")) {
            isValid = false;
            emailTF.setBorder(bordaVermelha);
        } else {
            emailTF.setBorder(bordaOriginal);
        }

        if (cpfTF.getText().trim().equals("") || cpfTF.getText().trim().length() != 14) {
            isValid = false;
            cpfTF.setBorder(bordaVermelha);
        } else {
            cpfTF.setBorder(bordaOriginal);
        }

        return isValid;
    }

    public void limparCampos() {
        nomeTF.setText("");
        nomeTF.setBorder(bordaOriginal);
        
        emailTF.setText("");
        emailTF.setBorder(bordaOriginal);
        
        dataNascimentoTF.setText("");
        dataNascimentoTF.setBorder(bordaOriginal);
        
        cpfTF.setText("");
        cpfTF.setBorder(bordaOriginal);
        
        sexoGrupoRB.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBT;
    private javax.swing.JFormattedTextField cpfTF;
    private javax.swing.JFormattedTextField dataNascimentoTF;
    private javax.swing.JTextField emailTF;
    private javax.swing.JRadioButton femininoRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton masculinoRB;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JRadioButton outroRB;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JButton salvarBT;
    private javax.swing.ButtonGroup sexoGrupoRB;
    // End of variables declaration//GEN-END:variables
}
